[package]
name = "web3_rust_toolkit"
authors = ["steinkirch"]
readme = "README.md"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
ether = "0.1.4"
hex = "0.4.3"
tokio = "1.23.0"
web3 = "0.18.0"
