[package]
name = "base64_encodings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
encode = "0.1.0"
error-chain = "0.12.4"
